-keep class com.outsystems.plugins.inappbrowser.** { *; }
-keep class com.outsystems.plugins.inappbrowser.osinappbrowserlib.** { *; }
-keep class kotlin.** { *; }
-dontwarn com.outsystems.plugins.inappbrowser.**